### ISSUE TITLE
memory leak in example

### ISSUE THREAD

**Issue by moyaldror** [ARMmbed/mbed-os-example-tls-socket#1]
In the `DISCONNECT` label you free the buffer but never the socket.
see:
https://github.com/ARMmbed/mbed-os-example-tls-socket/blob/3f678893646a09c85b059799ddcef16904bf4d66/main.cpp#L33
https://github.com/ARMmbed/mbed-os-example-tls-socket/blob/3f678893646a09c85b059799ddcef16904bf4d66/main.cpp#L57
and:
https://github.com/ARMmbed/mbed-os-example-tls-socket/blob/3f678893646a09c85b059799ddcef16904bf4d66/main.cpp#L98-L105

There is a need to add `delete socket;` to the `DISCONNECT` label.

**Comment by MarceloSalazar** [comment]
@SeppoTakalo
