### ISSUE TITLE
Question - What is the purpose of the +result

### ISSUE THREAD

**Issue by moyaldror** [ARMmbed/mbed-os-example-tls-socket#2]
What is the purpose of the `+result`? 
https://github.com/ARMmbed/mbed-os-example-tls-socket/blob/3f678893646a09c85b059799ddcef16904bf4d66/main.cpp#L79

**Comment by MarceloSalazar** [comment]
@SeppoTakalo can you please comment?

**Comment by SeppoTakalo** [comment]
Seems to be leftover from previous send loop.

I'll remove.
