### ISSUE TITLE
Stub readme file?

### ISSUE THREAD

**Issue by ConradBraam** [ARMmbed/mbed-os-example-tls-socket#4]
Is it possible to add a stub readme file which just links to the tls reference page, and states that this is a basic tls example...

To build and run the example a developer must install and configure a network [https://os.mbed.com/docs/latest/apis/network-interfaces.html] and then copy the binary to the target.
To run it:
mbed sterm

--- Terminal on COM25 - 9600,8,N,1 ---
TLSSocket Example.
Mbed OS version: 5.11.0

Connecting to network
[2K[90m[DBG ][TLSW]: mbedtls_ssl_conf_ca_chain()[0m
Connecting to api.ipify.org
[2K[39m[INFO][TLSW]: Starting TLS handshake with api.ipify.org[0m
[2K[90m[DBG ][TLSW]: mbedtls_ssl_setup()[0m
[2K[39m[INFO][TLSW]: TLS connection to api.ipify.org established[0m
[2K[90m[DBG ][TLSW]: Server certificate:
    cert. version     : 3
    serial number     : 92:0F:D1:B7:FE:4B:88:AE:B6:ED:5A:B0:C3:6C:56:68
    issuer name       : C=GB, ST=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO RSA Domain Validation Secure Server CA
    subject name      : OU=Domain Control Validated, OU=PositiveSSL Wildcard, CN=*.ipify.org
    issued  on        : 2018-01-24 00:00:00
    expires on        : 2021-01-23 23:59:59
    signed using      : RSA with SHA-256
    RSA key size      : 2048 bits
    basic constraints : CA=false
    subject alt name  : *.ipify.org, ipify.org
    key usage         : Digital Signature, Key Encipherment
    ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

[0m
[2K[39m[INFO][TLSW]: Certificate verification passed[0m
[2K[90m[DBG ][TLSW]: send 58[0m
HTTP/1.1 200 OK
Server: Cowboy
Connection: close
Content-Type: text/plain
Vary: Origin
Date: Mon, 10 Dec 2018 10:37:48 GMT
Content-Length: 14
Via: 1.1 vegur

217.***.***.***
[2K[39m[INFO][TLSW]: Closing TLS[0m
[2K[90m[DBG ][TLSW]: mbedtls_ssl_conf_ca_chain()[0m
Done

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-293*

**Comment by simonbutcher** [comment]
I'm not quite sure I understand what you're suggesting. 

We have two readmes, one at [the root](https://github.com/ARMmbed/mbed-os-example-tls/blob/master/README.md), and one at in the [sample directory](https://github.com/ARMmbed/mbed-os-example-tls/blob/master/tls-client/README.md).

Are you saying you'd rather we removed all that content, and put it on a webpage, and just make the readme point to that?

**Comment by ConradBraam** [comment]
I was expecting a readme in the example 
https://github.com/ARMmbed/mbed-os-example-tls-socket/**readme.md**
It's a consistency thing, where I am probably just expect a small redirecting link. to the "root".

**Comment by simonbutcher** [comment]
Sorry. I was confusing examples. This was mistakenly filed in the wrong JIRA board. I was talking about a different example.

**Comment by ConradBraam** [comment]
Thanks Simon. I nearly created a small readme myself for this project, to save time and just put in a pull request; but I'm not the expert on what we are trying to convey in this example.

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/mbed-os-example-tls-socket/commit/c78cc80c02ad215b284b10a73283a31deb72852b
