### ISSUE TITLE
compile time warning: String-based APIs are deprecated [since mbed-os-5.15] 

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbed-os-example-tls-socket#48]
The example uses string based API for `connect()`, even though it's deprecated
This was taken from [support forum](https://forums.mbed.com/t/warning-connect-is-deprecated-string-based-apis-are-deprecated-since-mbed-os-5-15/7347)

**Comment by RonEld** [comment]
This was already fixed in https://github.com/ARMmbed/mbed-os-example-tls-socket/pull/40

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCELL-2439*

**Comment by RonEld** [comment]
CLosing this ticket, as it was already fixed. To be released with 5.16
